const logoData = [
    
    //NFL
    
    {
        name:"Arizona Cardinals",
        group:"NFL",
        sport:"Football",
        tags: ["birds", "red", "animals"],
        vectorFile: "logos/NFL/vector/ARI.svg",
        png500: "logos/NFL/png/500/ARI.png",
        png1000: "logos/NFL/png/1000/ARI.png",
        colors: ["#97233f", "#ffffff"],
        colorsUsed: ["#97233f", "#ffb612", "#000000", "#ffffff"],
        year: "2005",
        alternatives:[],
        pastLogos:[],
        wordmark:,
        
        
        
    },
    {
        name:"Atlanta Falcons",
        group:"NFL",
        sport:"Football",
        tags: ["birds", "black", "animals"],
        vectorFile: "logos/NFL/vector/ATL.svg",
        png500: "logos/NFL/png/500/ATL.png",
        png1000: "logos/NFL/png/1000/ATL.png",
        colors: ["#a71930", "#ffffff", "#a5acaf", "#000000"],
        colorsUsed: ["#a71930", "#ffffff", "#a5acaf", "#000000"],
        year: "2003",
        
    },
    {
        name:"Baltimore Ravens",
        group:"NFL",
        sport:"Football",
        tags: ["birds", "purple", "animals"],
        vectorFile: "logos/NFL/vector/BAL.svg",
        png500: "logos/NFL/png/500/BAL.png",
        png1000: "logos/NFL/png/1000/BAL.png",
        colors: ["#241773", "#9e7c0c", "#000000"],
        colorsUsed: ["#241773", "#9e7c0c", "#000000", "#ffffff", "#c60c30"],
        year: "1999",
        
    },
    {
        name:"Buffalo Bills",
        group:"NFL",
        sport:"Football",
        tags: ["blue", "animals"],
        vectorFile: "logos/NFL/vector/BUF.svg",
        png500: "logos/NFL/png/500/BUF.png",
        png1000: "logos/NFL/png/1000/BUF.png",
        colors: ["#00338d", "#c60c30", "#ffffff", "#00274d"],
        colorsUsed: ["#00338d", "#c60c30", "#ffffff"],
        year: "1974",
        
    },
    {
        name:"Carolina Panthers",
        group:"NFL",
        sport:"Football",
        tags: ["cats","blue", "animals"],
        vectorFile: "logos/NFL/vector/CAR.svg",
        png500: "logos/NFL/png/500/CAR.png",
        png1000: "logos/NFL/png/1000/CAR.png",
        colors: ["#000000", "#0085ca", "#bfc0bf"],
        colorsUsed: ["#000000", "#0085ca", "#bfc0bf"],
        year: "2012",
        
    },
    {
        name:"Chicago Bears",
        group:"NFL",
        sport:"Football",
        tags: ["letters","orange", "C"],
        vectorFile: "logos/NFL/vector/CHI.svg",
        png500: "logos/NFL/png/500/CHI.png",
        png1000: "logos/NFL/png/1000/CHI.png",
        colors: ["#c83804", "#0b162a", "#ffffff"],
        colorsUsed: ["#c83804", "#0b162a", "#ffffff"],
        year: "1974",
        
    },
    {
        name:"Cincinnati Bengals",
        group:"NFL",
        sport:"Football",
        tags: ["letters","orange", "tiger", "striped", "B"],
        vectorFile: "logos/NFL/vector/CIN.svg",
        png500: "logos/NFL/png/500/CIN.png",
        png1000: "logos/NFL/png/1000/CIN.png",
        colors: ["#fb4f14", "#000000", "#ffffff"],
        colorsUsed: ["#fb4f14", "#000000", "#ffffff"],
        year: "2005",
        
    },
    {
        name:"Cleveland Browns",
        group:"NFL",
        sport:"Football",
        tags: ["helmet","orange"],
        vectorFile: "logos/NFL/vector/CLE.svg",
        png500: "logos/NFL/png/500/CLE.png",
        png1000: "logos/NFL/png/1000/CLE.png",
        colors: ["#ff3c00", "#311d00", "#ffffff"],
        colorsUsed: ["#ff3c00", "#311d00", "#ffffff"],
        year: "2015",
        
    },
    {
        name:"Dallas Cowboys",
        group:"NFL",
        sport:"Football",
        tags: ["star","blue"],
        vectorFile: "logos/NFL/vector/DAL.svg",
        png500: "logos/NFL/png/500/DAL.png",
        png1000: "logos/NFL/png/1000/DAL.png",
        colors: ["#002244", "#ffffff", "#00338d", "#b0b7bc"],
        colorsUsed: ["#002244", "#ffffff"],
        year: "1964",
        
    },
    {
        name:"Denver Broncos",
        group:"NFL",
        sport:"Football",
        tags: ["horse","animals", "orange"],
        vectorFile: "logos/NFL/vector/DEN.svg",
        png500: "logos/NFL/png/500/DEN.png",
        png1000: "logos/NFL/png/1000/DEN.png",
        colors: ["#002244", "#fb4f14", "#ffffff"],
        colorsUsed: ["#002244", "#fb4f14", "#ffffff"],
        year: "1997",
        
    },
    {
        name:"Detroit Lions",
        group:"NFL",
        sport:"Football",
        tags: ["blue","animals"],
        vectorFile: "logos/NFL/vector/DET.svg",
        png500: "logos/NFL/png/500/DET.png",
        png1000: "logos/NFL/png/1000/DET.png",
        colors: ["#0076b6", "#b0b7bc"],
        colorsUsed: ["#0076b6", "#ffffff", "#b0b7bc"],
        year: "2017",
        
    },
    {
        name:"Green Bay Packers",
        group:"NFL",
        sport:"Football",
        tags: ["letters","green", "G"],
        vectorFile: "logos/NFL/vector/GB.svg",
        png500: "logos/NFL/png/500/GB.png",
        png1000: "logos/NFL/png/1000/GB.png",
        colors: ["#203731", "#ffb612", "#ffffff"],
        colorsUsed: ["#203731", "#ffb612", "#ffffff"],
        year: "1980",
        
    },
    {
        name:"Houston Texans",
        group:"NFL",
        sport:"Football",
        tags: ["bull","blue", "red", "star", "animals"],
        vectorFile: "logos/NFL/vector/HOU.svg",
        png500: "logos/NFL/png/500/HOU.png",
        png1000: "logos/NFL/png/1000/HOU.png",
        colors: ["#04202f", "#a71930", "#ffffff"],
        colorsUsed: ["#04202f", "#a71930", "#ffffff"],
        year: "2002",
        
    },
     {
        name:"Indianapolis Colts",
        group:"NFL",
        sport:"Football",
        tags: ["horseshoe","blue", "horse"],
        vectorFile: "logos/NFL/vector/IND.svg",
        png500: "logos/NFL/png/500/IND.png",
        png1000: "logos/NFL/png/1000/IND.png",
        colors: ["#002c5f", "#ffffff"],
        colorsUsed: ["#002c5f", "#ffffff"],
        year: "2002",
        
    },
    {
        name:"Jacksonville Jaguars",
        group:"NFL",
        sport:"Football",
        tags: ["cats","teal", "gold", "animals"],
        vectorFile: "logos/NFL/vector/JAX.svg",
        png500: "logos/NFL/png/500/JAX.png",
        png1000: "logos/NFL/png/1000/JAX.png",
        colors: ["#006778", "#000000", "#9f792c"],
        colorsUsed: ["#006778", "#000000", "#9f792c", "#d7a22a", "#ffffff"],
        year: "2013",
        
    },
    {
        name:"Kansas City Chiefs",
        group:"NFL",
        sport:"Football",
        tags: ["letters","arrowhead", "red", "KC"],
        vectorFile: "logos/NFL/vector/KC.svg",
        png500: "logos/NFL/png/500/KC.png",
        png1000: "logos/NFL/png/1000/KC.png",
        colors: ["#e31837", "#ffffff", "#ffb612"],
        colorsUsed: ["#e31837", "#ffffff", "#000000"],
        year: "1972",
        
    },
    {
        name:"Los Angeles Chargers",
        group:"NFL",
        sport:"Football",
        tags: ["electric","lightning bolt", "yellow"],
        vectorFile: "logos/NFL/vector/LAC.svg",
        png500: "logos/NFL/png/500/LAC.png",
        png1000: "logos/NFL/png/1000/LAC.png",
        colors: ["#002a5e", "#ffffff", "#0080c6"],
        colorsUsed: ["#002a5e", "#ffffff", "#0080c6", "#ffc20e"],
        year: "2017",
        
    },
    {
        name:"Los Angeles Rams",
        group:"NFL",
        sport:"Football",
        tags: ["animals","horn"],
        vectorFile: "logos/NFL/vector/LAR.svg",
        png500: "logos/NFL/png/500/LAR.png",
        png1000: "logos/NFL/png/1000/LAR.png",
        colors: ["#002244", "#ffffff", "#b3995d"],
        colorsUsed: ["#002244", "#ffffff"],
        year: "2017",
        
    },
    {
        name:"Miami Dolphins",
        group:"NFL",
        sport:"Football",
        tags: ["animals","fish","sun"],
        vectorFile: "logos/NFL/vector/MIA.svg",
        png500: "logos/NFL/png/500/MIA.png",
        png1000: "logos/NFL/png/1000/MIA.png",
        colors: ["#008e97", "#ffffff", "#f26a24"],
        colorsUsed: ["#008e97", "#ffffff", "#005778", "#f26a24"],
        year: "2018",
        
    },
    {
        name:"Minnesota Vikings",
        group:"NFL",
        sport:"Football",
        tags: ["man","beard","blonde","purple"],
        vectorFile: "logos/NFL/vector/MIN.svg",
        png500: "logos/NFL/png/500/MIN.png",
        png1000: "logos/NFL/png/1000/MIN.png",
        colors: ["#4f2683", "#ffffff", "#ffc62f"],
        colorsUsed: ["#4f2683", "#ffffff", "#ffc62f", "#000000", "#e9bf9b"],
        year: "2013",
        
    },
    {
        name:"New England Patriots",
        group:"NFL",
        sport:"Football",
        tags: ["man","blue","star","wave"],
        vectorFile: "logos/NFL/vector/NE.svg",
        png500: "logos/NFL/png/500/NE.png",
        png1000: "logos/NFL/png/1000/NE.png",
        colors: ["#002244", "#ffffff", "#b0b7bc", "#c60c30"],
        colorsUsed: ["#002244", "#ffffff", "#b0b7bc", "#c60c30"],
        year: "2000",
        
    },
    {
        name:"New Orleans Saints",
        group:"NFL",
        sport:"Football",
        tags: ["fleur-de-lis","fleur-de-lys","gold"],
        vectorFile: "logos/NFL/vector/NO.svg",
        png500: "logos/NFL/png/500/NO.png",
        png1000: "logos/NFL/png/1000/NO.png",
        colors: ["#d3bc8d", "#ffffff", "#000000"],
        colorsUsed: ["#d3bc8d", "#ffffff", "#000000"],
        year: "2012",
        
    },
    
]